embeddedEditorPackages=GA Patch 5.1
isReadOnly=false
packPath=C\:\\GOG Games\\SPORE\\DataEP1
packPathType=CUSTOM
packageName=x2_Creature_Stage_Length.package
showOnlyModded=true
sources="Spore (Game & Graphics)"
